version: '3.5'

services:

  socs-app:
    container_name: socs-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=development
